[project]
name = "opencity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "fastdtw>=0.3.4",
    "h5py>=3.14.0",
    "numpy>=1.26.4,<2",
    "pandas>=2.3.3",
    "scipy>=1.13.1",
    "tables>=3.9.2",
    "torch==2.4.1",
    "torchaudio==2.4.1",
    "torchvision==0.19.1",
    "tqdm>=4.67.3",
    "tslearn>=0.6.4",
]

[tool.uv]
extra-index-url = ["https://download.pytorch.org/whl/cu124"]
index-strategy = "unsafe-best-match"
